### ISSUE TITLE
Question about gradient scale

### ISSUE THREAD

**Issue by Spazierganger** [uclnlp/torch-imle#3]
Dear contributors,
I found in [tf-imle repo](https://github.com/nec-research/tf-imle/blob/main/DVAE/discrete-VAE-experiments-neurips.ipynb), the gradient is divided by `self._lambda`, I wonder why in this repo it is not scaled.

**Comment by pminervini** [comment]
Great point! It is scaled in the new version of the library (https://github.com/EdinburghNLP/torch-adaptive-imle), will propagate the changes here :)
